### ISSUE TITLE
On Python 3 installation

### ISSUE THREAD

**Issue by jtkSource** [gemfire/py-gemfire-rest#2]
Hi,

Couldn't install on python3 because logging is an old version in PYPI and print is in an old format

I removed loggin in setup.py as its already part of python and removed the print statements in
gemfire/Region.py
gemfire/GemfireClient.py

Thanks,
Jubin

**Comment by jdeppe-pivotal** [comment]
Perhaps you'd like to submit a pull request? :)

**Comment by jtkSource** [comment]
hmm.. ok :) thought it would be easier to let you know.. there are a few other changes also.. will add those in
